---
twitter: https://twitter.com/NewNetNinja
github: ''
linkedin: https://www.linkedin.com/in/delfosbram/
youtube: ''
dribbble: ''
instagram: ''
facebook: ''
medium: ''
patreon: ''
paypal: ''
unsplash: ''
